flye:
  extra_args: ""
  
hifiasm:
  extra_args: ""

medaka:
  model: "r1041_e82_400bps_sup_v5.0.0"  # adjust to your flowcell/basecaller
  extra_args: ""

threads:
  hifiasm: 20
  flye: 38
  medaka: 8